#!/bin/bash

if [ "X$1" = "X" ]; then
echo "usage: `basename $0` <host>"
exit 1
fi

if [ "X$SSH_AUTH_SOCK" = "X" ]; then
 eval `ssh-agent -s`
 ssh-add $HOME/.ssh/id_rsa
fi


CP="/tmp/ssh_${1:0:50}_%r_%p"

ssh -C -t -o "ControlPath=$CP" $@ 'tmux -L artur attach'

if [ $? != 0 ]
then
    ssh -C -t -o "ControlPath=$CP" $@ "tmux -L artur -f ~/.art/.tmux-art new"
fi

