#!/bin/bash

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
  platform='macos'
fi

if [[ $platform == 'linux' ]]; then
    cd $(dirname "$(readlink -f $0)")
elif [[ $platform == 'macos' ]]; then
    cd $(dirname $0)
    cd $(dirname "$(readlink -n $0)")
fi

if [ "X$1" = "X" ]; then
echo "usage: `basename $0` <host>"
exit 1
fi

if [ "X$SSH_AUTH_SOCK" = "X" ]; then
 eval `ssh-agent -s`
 ssh-add $HOME/.ssh/id_rsa
fi

echo "$@" >> ~/assh.log

CP="/tmp/ssh_${1:0:50}_%r_%p"

if ! ssh -t -o "ControlPath=$CP" $@ '[ -d .art ]'; then
    read -p "No, do you want to install[Yy]? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        ansible-playbook -i $@, ${PWD}/assh-play/install.yml -e server=$@
    fi
fi

ssh -C -t -o "ControlPath=$CP" $@ 'tmux -L artur attach'

if [ $? != 0 ]; then
    ssh -C -t -o "ControlPath=$CP" $@ "tmux -L artur -f ~/.art/.tmux-art new"
fi
