#!/usr/bin/env bash

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
  platform='macos'
fi

if [[ $platform == 'linux' ]]; then
    cd $(dirname "$(readlink -f $0)")
elif [[ $platform == 'macos' ]]; then
    cd $(dirname $0)
    cd $(dirname "$(readlink -n $0)")
fi

CP="/tmp/ssh_${1:0:50}_%r_%p"
SSH="/usr/bin/ssh -o ConnectTimeout=10 -o BatchMode=yes -o ControlPath=\"$CP\""

if [ "X$1" = "X" ]; then
echo "usage: `basename $0` <host>"
exit 1
fi

if [[ $($SSH $@ "echo YEP") ]];
then
    echo Key installed
    ansible-playbook -i $@, ${PWD}/assh-play/install.yml -e server=$@
else
    echo Key NOT installed
    ansible-playbook -i $@, ${PWD}/assh-play/install.yml -k -e server=$@
fi

