---
language: go

go:
  - 1.5.2

env:
  matrix:
    - COMPONENT=books_bot

before_install:
  - env
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
    fi
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -vE '(\.md$)|(^(docs|examples))/' || {
      echo "Only docs were updated, stopping build process."
      exit
    }

script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
    fi
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep "$COMPONENT" || {
      echo "$COMPONENT wasn't updated, stopping build process"
      exit
    }
    # if [ "$COMPONENT" = books_bot ]; then
        # cd $COMPONENT
        cd books_bot
        go test
        GOOS=linux GOARCH=amd64 go build -o ewokru_bot
    # fi

branches:
  only:
  - master

git:
  depth: 3
install:
  - go get golang.org/x/net/html
  - go get github.com/rockneurotiko/go-tgbot
