#!/usr/bin/ansible-playbook -v
---

- name: Initialization
  become: False
  hosts: "{{ server }}"
  # gather_facts: False
  tasks:

    - file: path="{{ item }}" state=directory mode=0700 owner={{ ansible_user_id }}
      with_items:
        - "/home/{{ ansible_user_id }}/.ssh"
        - "/home/{{ ansible_user_id}}/.mc"

    - name: Add ssh_key
      authorized_key: user={{ ansible_user_id }} key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"

    - name: config dir
      file: path=/home/{{ ansible_user_id}}/.art state=directory mode=0755

    - name: copy tmux config
      copy: src=tmux dest=/home/{{ ansible_user_id}}/.art/.tmux-art mode=0644

    - name: copy zsh config
      copy: src=zshrc dest=/home/{{ ansible_user_id}}/.art/.zshrc mode=0644

    - name: copy mc config
      copy: src={{ item }} dest="/home/{{ ansible_user_id}}/.mc/" mode=0644
      with_items:
        - "ini"
        - "panels.ini"

    - include: apt.yml
      become: True
      when: ansible_pkg_mgr == 'apt'

    - include: yum.yml
      become: True
      when: ansible_pkg_mgr == 'yum'

    #- name: Kill tmux sessions
      #command: killall tmux
      #ignore_errors: True
      #tags: killtmux

    - file: path={{ item }} state=absent
      with_items:
        - "/home/{{ ansible_user_id}}/.tmux-art"
        - "/home/{{ ansible_user_id}}/.zshrc-art"
        - "/home/{{ ansible_user_id}}/.zsh_history-art"
      tags: clean

